apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: optaplanner
  name: optaplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optaplanner
  template:
    metadata:
      labels:
        app: optaplanner
    spec:
      containers:
        - name: release-name-optaplanner-workbench
          env: 
          - name: JAVA_OPTS
            value: "-Xms256m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
          image: jboss/jbpm-workbench-showcase:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 50
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 50
            successThreshold: 1
            timeoutSeconds: 300
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8001
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 300
