apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
  name: optaplanner
spec:
  tls:
    - hosts:
      - optaplanner.inovio.tech-stack.dev
      secretName: optaplanner-inovio-tls
  rules:
  - host: optaplanner.inovio.tech-stack.dev
    http:
      paths:
      - backend:
          serviceName: release-name-optaplanner-server
          servicePort: opta
        path: /
