apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: optaplanner
spec:
  rules:
  - host: optaplanner.clearslideng.com
    http:
      paths:
      - backend:
          serviceName: release-name-optaplanner-server
          servicePort: opta
        path: /
