apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
  name: db
  namespace: default
spec:
  tls:
    - hosts:
      - orientdb.inovio.co
      secretName: db-inovio-tls
  rules:
  - host: orientdb.inovio.co
    http:
      paths:
      - backend:
          serviceName: release-name-orientdb-svc
          servicePort: 2480
        path: /
