---
# Source: orientdb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-orientdb-secret
  labels:
    app: orientdb
    chart: orientdb-0.1.2
    release: release-name
    heritage: Tiller
data:
  
  root-password: "dGllenVhNURldXgK"
  
